//
// Created by vnrju on 08/22/2022.
//
/** @file */

#ifndef STREAMING_MODULE_CAMERA_H
#define STREAMING_MODULE_CAMERA_H

#include <esp_camera.h>
#include <freertos/FreeRTOS.h>
#include <freertos/queue.h>

#ifdef CONFIG_SOFTEX_CAMERA_LEDC_TIMER_0
#define SOFTEX_CAMERA_LEDC_TIMER LEDC_TIMER_0
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_TIMER_1
#define SOFTEX_CAMERA_LEDC_TIMER LEDC_TIMER_1
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_TIMER_2
#define SOFTEX_CAMERA_LEDC_TIMER LEDC_TIMER_2
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_TIMER_3
#define SOFTEX_CAMERA_LEDC_TIMER LEDC_TIMER_3
#endif

#ifdef CONFIG_SOFTEX_CAMERA_LEDC_CHANNEL_0
#define SOFTEX_CAMERA_LEDC_CHANNEL LEDC_CHANNEL_0
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_CHANNEL_1
#define SOFTEX_CAMERA_LEDC_CHANNEL LEDC_CHANNEL_1
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_CHANNEL_2
#define SOFTEX_CAMERA_LEDC_CHANNEL LEDC_CHANNEL_2
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_CHANNEL_3
#define SOFTEX_CAMERA_LEDC_CHANNEL LEDC_CHANNEL_3
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_CHANNEL_4
#define SOFTEX_CAMERA_LEDC_CHANNEL LEDC_CHANNEL_4
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_CHANNEL_5
#define SOFTEX_CAMERA_LEDC_CHANNEL LEDC_CHANNEL_5
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_CHANNEL_6
#define SOFTEX_CAMERA_LEDC_CHANNEL LEDC_CHANNEL_6
#endif
#ifdef CONFIG_SOFTEX_CAMERA_LEDC_CHANNEL_7
#define SOFTEX_CAMERA_LEDC_CHANNEL LEDC_CHANNEL_7
#endif

#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_RGB565
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_RGB565
#endif
#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_YUV422
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_YUV422
#endif
#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_YUV420
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_YUV420
#endif
#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_GRAYSCALE
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_GRAYSCALE
#endif
#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_JPEG
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_JPEG
#endif
#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_RGB888
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_RGB888
#endif
#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_RAW
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_RAW
#endif
#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_RGB444
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_RGB444
#endif
#ifdef CONFIG_SOFTEX_CAMERA_PIXFORMAT_RGB555
#define SOFTEX_CAMERA_PIXFORMAT PIXFORMAT_RGB555
#endif

#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_96X96
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_96X96
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_QQVGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_QQVGA
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_QCIF
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_QCIF
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_HQVGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_HQVGA
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_240X240
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_240X240
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_QVGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_QVGA
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_CIF
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_CIF
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_HVGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_HVGA
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_VGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_VGA
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_SVGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_SVGA
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_XGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_XGA
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_HD
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_HD
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_SXGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_SXGA
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FRAMESIZE_UXGA
#define SOFTEX_CAMERA_FRAMESIZE FRAMESIZE_UXGA
#endif

#ifdef SOFTEX_CAMERA_AI_THINKER // ESPCAM AI Thinker
#define SOFTEX_CAMERA_PIN_PWDN 32
#define SOFTEX_CAMERA_PIN_RESET -1
#define SOFTEX_CAMERA_PIN_XCLK 0
#define SOFTEX_CAMERA_PIN_SDA 26
#define SOFTEX_CAMERA_PIN_SCL 27
#define SOFTEX_CAMERA_PIN_D7 35
#define SOFTEX_CAMERA_PIN_D6 34
#define SOFTEX_CAMERA_PIN_D5 39
#define SOFTEX_CAMERA_PIN_D4 36
#define SOFTEX_CAMERA_PIN_D3 21
#define SOFTEX_CAMERA_PIN_D2 19
#define SOFTEX_CAMERA_PIN_D1 18
#define SOFTEX_CAMERA_PIN_D0 5
#define SOFTEX_CAMERA_PIN_VSYNC 25
#define SOFTEX_CAMERA_PIN_HREF 23
#define SOFTEX_CAMERA_PIN_PCLK 22
#endif
#ifdef SOFTEX_CAMERA_WROVER_KIT // WROVER Kit v4.1
#define SOFTEX_CAMERA_PIN_PWDN -1
#define SOFTEX_CAMERA_PIN_RESET 0
#define SOFTEX_CAMERA_PIN_XCLK 21
#define SOFTEX_CAMERA_PIN_SDA 26
#define SOFTEX_CAMERA_PIN_SCL 27
#define SOFTEX_CAMERA_PIN_D7 35
#define SOFTEX_CAMERA_PIN_D6 34
#define SOFTEX_CAMERA_PIN_D5 39
#define SOFTEX_CAMERA_PIN_D4 36
#define SOFTEX_CAMERA_PIN_D3 19
#define SOFTEX_CAMERA_PIN_D2 18
#define SOFTEX_CAMERA_PIN_D1 5
#define SOFTEX_CAMERA_PIN_D0 4
#define SOFTEX_CAMERA_PIN_VSYNC 25
#define SOFTEX_CAMERA_PIN_HREF 23
#define SOFTEX_CAMERA_PIN_PCLK 22
#endif
#ifdef SOFTEX_CAMERA_TTGO // TTGO
#define SOFTEX_CAMERA_PIN_PWDN 25
#define SOFTEX_CAMERA_PIN_RESET 0
#define SOFTEX_CAMERA_PIN_XCLK 13
#define SOFTEX_CAMERA_PIN_SDA 4
#define SOFTEX_CAMERA_PIN_SCL 22
#define SOFTEX_CAMERA_PIN_D7 21
#define SOFTEX_CAMERA_PIN_D6 35
#define SOFTEX_CAMERA_PIN_D5 2
#define SOFTEX_CAMERA_PIN_D4 14
#define SOFTEX_CAMERA_PIN_D3 33
#define SOFTEX_CAMERA_PIN_D2 39
#define SOFTEX_CAMERA_PIN_D1 32
#define SOFTEX_CAMERA_PIN_D0 0
#define SOFTEX_CAMERA_PIN_VSYNC 23
#define SOFTEX_CAMERA_PIN_HREF 36
#define SOFTEX_CAMERA_PIN_PCLK 15
#endif
#ifdef SOFTEX_CAMERA_SOFTEX
#define SOFTEX_CAMERA_PIN_PWDN CONFIG_SOFTEX_CAMERA_PIN_PWDN
#define SOFTEX_CAMERA_PIN_RESET CONFIG_SOFTEX_CAMERA_PIN_RESET
#define SOFTEX_CAMERA_PIN_XCLK CONFIG_SOFTEX_CAMERA_PIN_XCLK
#define SOFTEX_CAMERA_PIN_SDA 48//CONFIG_SOFTEX_CAMERA_PIN_SDA
#define SOFTEX_CAMERA_PIN_SCL 16//CONFIG_SOFTEX_CAMERA_PIN_SCL
#define SOFTEX_CAMERA_PIN_D7 CONFIG_SOFTEX_CAMERA_PIN_D7
#define SOFTEX_CAMERA_PIN_D6 CONFIG_SOFTEX_CAMERA_PIN_D6
#define SOFTEX_CAMERA_PIN_D5 CONFIG_SOFTEX_CAMERA_PIN_D5
#define SOFTEX_CAMERA_PIN_D4 CONFIG_SOFTEX_CAMERA_PIN_D4
#define SOFTEX_CAMERA_PIN_D3 14//CONFIG_SOFTEX_CAMERA_PIN_D3
#define SOFTEX_CAMERA_PIN_D2 CONFIG_SOFTEX_CAMERA_PIN_D2
#define SOFTEX_CAMERA_PIN_D1 CONFIG_SOFTEX_CAMERA_PIN_D1
#define SOFTEX_CAMERA_PIN_D0 CONFIG_SOFTEX_CAMERA_PIN_D0
#define SOFTEX_CAMERA_PIN_VSYNC CONFIG_SOFTEX_CAMERA_PIN_VSYNC
#define SOFTEX_CAMERA_PIN_HREF CONFIG_SOFTEX_CAMERA_PIN_HREF
#define SOFTEX_CAMERA_PIN_PCLK CONFIG_SOFTEX_CAMERA_PIN_PCLK
#endif
#if 1 | SOFTEX_CAMERA_CUSTOM_ADAPTER // Softex (Custom Adapter)
#define SOFTEX_CAMERA_PIN_PWDN 45
#define SOFTEX_CAMERA_PIN_RESET -1
#define SOFTEX_CAMERA_PIN_XCLK 8
#define SOFTEX_CAMERA_PIN_SDA 48
#define SOFTEX_CAMERA_PIN_SCL 16
#define SOFTEX_CAMERA_PIN_D7 26
#define SOFTEX_CAMERA_PIN_D6 41
#define SOFTEX_CAMERA_PIN_D5 3
#define SOFTEX_CAMERA_PIN_D4 1
#define SOFTEX_CAMERA_PIN_D3 42
#define SOFTEX_CAMERA_PIN_D2 47
#define SOFTEX_CAMERA_PIN_D1 15
#define SOFTEX_CAMERA_PIN_D0 38
#define SOFTEX_CAMERA_PIN_VSYNC 39
#define SOFTEX_CAMERA_PIN_HREF 46
#define SOFTEX_CAMERA_PIN_PCLK 40
#endif

/** Frequência do clock da câmera */
#define SOFTEX_CAMERA_XCLK_FREQ_HZ CONFIG_SOFTEX_CAMERA_XCLK_FREQ_HZ

/** Qualidade da captura jpeg */
#define SOFTEX_CAMERA_JPEG_QUALITY CONFIG_SOFTEX_CAMERA_JPEG_QUALITY

/** @brief Quantidade de framebuffers disponíveis */
#define SOFTEX_CAMERA_FB_COUNT CONFIG_SOFTEX_CAMERA_FB_COUNT

#ifdef CONFIG_SOFTEX_CAMERA_FB_IN_PSRAM
#define SOFTEX_CAMERA_FB_LOCATION CAMERA_FB_IN_PSRAM
#endif
#ifdef CONFIG_SOFTEX_CAMERA_FB_IN_DRAM
#define SOFTEX_CAMERA_FB_LOCATION CAMERA_FB_IN_DRAM
#endif

#ifdef CONFIG_SOFTEX_CAMERA_GRAB_WHEN_EMPTY
#define SOFTEX_CAMERA_GRAB_MODE CAMERA_GRAB_WHEN_EMPTY
#endif
#ifdef CONFIG_SOFTEX_CAMERA_GRAB_LATEST
#define SOFTEX_CAMERA_GRAB_MODE CAMERA_GRAB_LATEST
#endif

#ifdef CONFIG_SOFTEX_CAMERA_CAPTURE_TASK_STACK_SIZE
#define SOFTEX_CAMERA_CAPTURE_TASK_STACK_SIZE CONFIG_SOFTEX_CAMERA_CAPTURE_TASK_STACK_SIZE
#endif

/**
 * @brief Configura a câmera utilizando os valores selecionados através do `menuconfig`
 *
 * @param output_queue Handle to queue used to send captured frames
 *
 * @return
 *      - 0 caso a câmera tenha sido configurada com sucesso
 *      - -ENXIO Não foi possível encontrar o sensor
 * */
int camera_setup(QueueHandle_t output_queue);

/**
 * @brief Cria a tarefa de capturar as imagens da câmera
 *
 * @return
 */
int camera_start();

#endif //STREAMING_MODULE_CAMERA_H
